# -*- coding: utf-8 -*-
"""sales_data_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11s6s0xw5w4TsARy7jlS9oOcqJmnGYFGB

# 1. Instalación de dependencias con resolución de conflictos
# Forzamos la actualización de LangChain y sus integraciones para evitar errores de compatibilidad
"""

!pip install -q -U langchain langchain-community langchain-experimental langchain-mistralai pandas faiss-cpu tiktoken requests==2.32.4

import requests
import langchain_core
import langchain_experimental
import pandas as pd
import langchain

print(f"Instalación completada.")
print(f"Versión de requests: {requests.__version__}")
print(f"Versión de langchain-core: {langchain_core.__version__}")
print(f"Versión de pandas: {pd.__version__}")
print(f"Versión de langchain: {langchain.__version__}")

"""### 2. Normalización y Limpieza de Datos
Antes de pasar los datos a los agentes de IA, debemos asegurarnos de que estén limpios y en un formato estándar.
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 1. Carga con codificación correcta
df_raw = pd.read_csv('sales_data_sample.csv', encoding='latin1')

# 2. Limpieza básica: nombres de columnas en minúsculas y sin espacios
df_raw.columns = df_raw.columns.str.strip().str.lower()

# 3. Conversión de tipos
if 'orderdate' in df_raw.columns:
    df_raw['orderdate'] = pd.to_datetime(df_raw['orderdate'])

# 4. Manejo de nulos (Solo si la columna existe)
if 'state' in df_raw.columns:
    df_raw['state'] = df_raw['state'].fillna('N/A')
else:
    print("Nota: La columna 'state' no se encontró en el dataset.")

# 5. Normalización de la columna 'sales' (Escalado entre 0 y 1)
if 'sales' in df_raw.columns:
    scaler = MinMaxScaler()
    df_raw['sales_normalized'] = scaler.fit_transform(df_raw[['sales']])

# Guardamos el dataframe limpio para los siguientes pasos
df = df_raw.copy()

print("Datos procesados y listos.")
display(df.head())

import pandas as pd
import os

# Usamos el archivo que el usuario subió localmente
file_path = 'sales_data_sample.csv'

if os.path.exists(file_path):
    try:
        # Cargar el archivo local
        df = pd.read_csv(file_path, encoding='latin1')

        # Normalizar nombres de columnas para que el bot no se confunda
        df.columns = df.columns.str.strip().str.lower()

        print(f"✅ ¡Éxito! Archivo local cargado correctamente.")
        print(f"Total de registros encontrados: {len(df)}")
        display(df.head(3))
    except Exception as e:
        print(f"❌ Error al leer el archivo local: {e}")
else:
    print(f"❌ No se encontró el archivo '{file_path}' en la carpeta de archivos (panel izquierdo).")

"""## 🤖 Asistente de Ventas Maestro
Esta celda inicializa el chatbot híbrido que puede realizar cálculos complejos sobre el CSV y responder preguntas narrativas con memoria de conversación.
"""

from langchain_core.callbacks.manager import handle_event
import os
import pandas as pd
import langchain
from google.colab import userdata
from langchain_mistralai.chat_models import ChatMistralAI
from langchain_mistralai.embeddings import MistralAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import CSVLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

# 1. Configuración de Identidad y LLM
api_key = userdata.get('API_KEY_MISTRAL')
llm = ChatMistralAI(mistral_api_key=api_key, model='open-mixtral-8x7b', temperature=0)

prefix = """
Eres un experto analista de datos de ventas.
El dataframe 'df' contiene 2,823 registros detallados.
Responde siempre de forma profesional y en español.
"""

try:
    # 2. Configurar RAG (Búsqueda de contexto)
    loader = CSVLoader(file_path='sales_data_sample.csv', encoding='latin1')
    docs = loader.load()
    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    embeddings = MistralAIEmbeddings(mistral_api_key=api_key)
    vectorstore = FAISS.from_documents(splitter.split_documents(docs), embeddings)
    memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True)
    rag_chain = ConversationalRetrievalChain.from_llm(llm=llm, retriever=vectorstore.as_retriever(), memory=memory)

    # 3. Configurar Agente de Pandas (Cálculos)
    agente_pandas = create_pandas_dataframe_agent(
        llm,
        df,
        prefix=prefix,
        verbose=False,
        allow_dangerous_code=True,
        handle_parsing_errors=True,
        agent_type="tool-calling"
    )

    print("✅ SISTEMA UNIFICADO LISTO")
except Exception as e:
    print(f"❌ Error en configuración: {e}")

"""### 💬 Interfaz del Asistente
Ejecuta esta celda para iniciar la conversación con el experto en ventas.
"""

print("====================================================")
print("🤖 ASISTENTE DE VENTAS MAESTRO ACTIVADO")
print("====================================================")
print("Escribe tu pregunta (o 'salir' para finalizar)")

while True:
    entrada = input("\n👉 Tu pregunta: ").strip()
    if not entrada: continue
    if entrada.lower() in ['salir', 'exit', 'quit']:
        print("👋 ¡Hasta pronto!")
        break

    # Enrutamiento inteligente
    keywords = ['cuanto', 'cuántos', 'promedio', 'suma', 'total', 'máximo', 'mínimo', 'calcular', 'ventas']
    usa_agente = any(word in entrada.lower() for word in keywords)

    try:
        if usa_agente:
            print("⏳ [Calculando datos numéricos...]")
            res = agente_pandas.invoke({"input": entrada})
            print(f"\n💬 {res['output']}")
        else:
            print("⏳ [Buscando en historial y contexto...]")
            res = rag_chain.invoke({"question": entrada})
            print(f"\n💬 {res['answer']}")
    except Exception as e:
        print(f"❌ Error: {e}")

"""### 📚 Ejemplo de RAG usando LCEL y `chain.invoke()`
Esta es la forma recomendada por LangChain para construir cadenas personalizadas de manera declarativa.
"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

# 1. Definir el Prompt
template = """Responde la pregunta basándote únicamente en el siguiente contexto:
{context}

Pregunta: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

# 2. Crear la cadena (Chain) usando el pipe operador |
# Esta cadena:
# - Recupera el contexto
# - Lo pasa al prompt junto con la pregunta
# - Envía el resultado al LLM
# - Parsea la salida a texto simple
rag_chain_lcel = (
    {"context": vectorstore.as_retriever(), "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# 3. Ejecutar usando .invoke()
pregunta_ejemplo = "¿Qué líneas de producto existen en el dataset?"
respuesta = rag_chain_lcel.invoke(pregunta_ejemplo)

print(f"Pregunta: {pregunta_ejemplo}")
print(f"Respuesta: {respuesta}")

"""### 💬 Interfaz Manual para el RAG LCEL
Ejecuta esta celda para chatear con la cadena que acabamos de crear.
"""

print("Conversación manual con RAG (LCEL) iniciada. Escribe 'salir' para terminar.")

while True:
    usuario_pregunta = input("\n❓ Tu pregunta: ").strip()

    if usuario_pregunta.lower() in ['salir', 'exit', 'quit']:
        print("👋 ¡Sesión terminada!")
        break

    if not usuario_pregunta:
        continue

    try:
        # Invocamos la cadena con la entrada del usuario
        respuesta_lcel = rag_chain_lcel.invoke(usuario_pregunta)
        print(f"\n🤖 Respuesta: {respuesta_lcel}")
    except Exception as e:
        print(f"❌ Ocurrió un error: {e}")

"""# 📋 README: Resumen de Resultados y Proceso

Este documento detalla los hallazgos y la arquitectura del sistema de análisis de ventas implementado en este notebook.

## 1. Preparación del Entorno
- **Resultado**: Instalación exitosa de librerías críticas como `langchain`, `langchain-mistralai`, `pandas` y `faiss-cpu`.
- **Versiones Clave**:
  - `langchain-core`: 0.3.86
  - `pandas`: 2.2.2
  - Se garantizó la compatibilidad con `requests 2.32.4` para evitar conflictos de dependencias.

## 2. Limpieza y Normalización de Datos
Se procesó el archivo `sales_data_sample.csv` con los siguientes pasos:
- **Estandarización**: Nombres de columnas convertidos a minúsculas y sin espacios.
- **Tipos de Datos**: Transformación de la columna `orderdate` a formato datetime.
- **Tratamiento de Nulos**: Se imputaron valores 'N/A' en la columna `state`.
- **Feature Engineering**: Se creó `sales_normalized` mediante un escalado `MinMaxScaler` (valores entre 0 y 1), ideal para análisis comparativos.

## 3. Arquitectura del Asistente Maestro (Híbrido)
Implementamos un sistema que utiliza dos motores distintos según la consulta del usuario:
- **Agente de Pandas (Cálculos Numéricos)**: Capaz de ejecutar código para responder preguntas complejas (ej. promedios, máximos, sumas de ventas).
- **Motor RAG (Contexto Narrativo)**: Utiliza `FAISS` como base de datos vectorial para buscar información textual específica en los registros.
- **Memoria**: El sistema mantiene un historial de conversación para respuestas coherentes.

## 4. Implementación RAG con LCEL
Se creó una cadena declarativa (LangChain Expression Language) que optimiza el flujo de trabajo:
1. **Recuperación**: Busca los fragmentos más relevantes en el dataset.
2. **Prompt**: Enmarca la pregunta dentro del contexto recuperado.
3. **LLM**: Genera una respuesta precisa basada únicamente en los datos proporcionados.

### Hallazgos Clave en los Datos
- **Segmentación**: Se identificó que la línea de productos dominante en los fragmentos analizados es **'Trucks and Buses'**.
- **Cronología**: El sistema detectó correctamente fechas de operaciones, como una venta registrada el **24 de junio de 2004**.
- **Volumen**: El dataset cuenta con **2,823 registros** listos para ser consultados.
"""